# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5fa7c5a92f2f5b2918174231e11def3e8ef2ca6d2dae417114c4823e77bc5c633cd3c769f3c1dad11979f704303ea81564a6b4b397d59c3c4ef6555dc7bbb99

test:
  secret_key_base: 3d6d43bbecd90d9061d84a82564a8b58f325d423ef11b924b187dac5b240aa15b9efc621f06e980e9968d5c639ea95782905d94a04e1c4c212940d3d71afaffb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
